package com.juju.sport.admin.manager.pojo;

import java.util.Date;

public class AccountMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_account_menu.id
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_account_menu.admin_account_id
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    private String adminAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_account_menu.menu_id
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_account_menu.create_time
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_account_menu.create_person
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_account_menu.last_update_time
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_account_menu.last_update_person
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_account_menu.stat
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_account_menu.id
     *
     * @return the value of admin_account_menu.id
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_account_menu.id
     *
     * @param id the value for admin_account_menu.id
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_account_menu.admin_account_id
     *
     * @return the value of admin_account_menu.admin_account_id
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public String getAdminAccountId() {
        return adminAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_account_menu.admin_account_id
     *
     * @param adminAccountId the value for admin_account_menu.admin_account_id
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public void setAdminAccountId(String adminAccountId) {
        this.adminAccountId = adminAccountId == null ? null : adminAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_account_menu.menu_id
     *
     * @return the value of admin_account_menu.menu_id
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_account_menu.menu_id
     *
     * @param menuId the value for admin_account_menu.menu_id
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_account_menu.create_time
     *
     * @return the value of admin_account_menu.create_time
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_account_menu.create_time
     *
     * @param createTime the value for admin_account_menu.create_time
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_account_menu.create_person
     *
     * @return the value of admin_account_menu.create_person
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_account_menu.create_person
     *
     * @param createPerson the value for admin_account_menu.create_person
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_account_menu.last_update_time
     *
     * @return the value of admin_account_menu.last_update_time
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_account_menu.last_update_time
     *
     * @param lastUpdateTime the value for admin_account_menu.last_update_time
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_account_menu.last_update_person
     *
     * @return the value of admin_account_menu.last_update_person
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_account_menu.last_update_person
     *
     * @param lastUpdatePerson the value for admin_account_menu.last_update_person
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_account_menu.stat
     *
     * @return the value of admin_account_menu.stat
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_account_menu.stat
     *
     * @param stat the value for admin_account_menu.stat
     *
     * @mbggenerated Mon Sep 08 21:16:25 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}