package com.juju.sport.admin.manager.pojo;

import java.util.Date;

import lombok.ToString;

@ToString
public class MenuGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu_group.id
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu_group.menu_group_name
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    private String menuGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu_group.menu_group_order
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    private Integer menuGroupOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu_group.create_time
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu_group.create_person
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu_group.last_update_time
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu_group.last_update_person
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu_group.stat
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu_group.id
     *
     * @return the value of admin_menu_group.id
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu_group.id
     *
     * @param id the value for admin_menu_group.id
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu_group.menu_group_name
     *
     * @return the value of admin_menu_group.menu_group_name
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public String getMenuGroupName() {
        return menuGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu_group.menu_group_name
     *
     * @param menuGroupName the value for admin_menu_group.menu_group_name
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public void setMenuGroupName(String menuGroupName) {
        this.menuGroupName = menuGroupName == null ? null : menuGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu_group.menu_group_order
     *
     * @return the value of admin_menu_group.menu_group_order
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public Integer getMenuGroupOrder() {
        return menuGroupOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu_group.menu_group_order
     *
     * @param menuGroupOrder the value for admin_menu_group.menu_group_order
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public void setMenuGroupOrder(Integer menuGroupOrder) {
        this.menuGroupOrder = menuGroupOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu_group.create_time
     *
     * @return the value of admin_menu_group.create_time
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu_group.create_time
     *
     * @param createTime the value for admin_menu_group.create_time
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu_group.create_person
     *
     * @return the value of admin_menu_group.create_person
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu_group.create_person
     *
     * @param createPerson the value for admin_menu_group.create_person
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu_group.last_update_time
     *
     * @return the value of admin_menu_group.last_update_time
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu_group.last_update_time
     *
     * @param lastUpdateTime the value for admin_menu_group.last_update_time
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu_group.last_update_person
     *
     * @return the value of admin_menu_group.last_update_person
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu_group.last_update_person
     *
     * @param lastUpdatePerson the value for admin_menu_group.last_update_person
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu_group.stat
     *
     * @return the value of admin_menu_group.stat
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu_group.stat
     *
     * @param stat the value for admin_menu_group.stat
     *
     * @mbggenerated Thu Aug 28 14:42:12 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}