package com.juju.sport.order.mapper;

import com.juju.sport.order.pojo.Orders;
import com.juju.sport.order.pojo.OrdersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    int countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    Orders selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_orders
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    int updateByPrimaryKey(Orders record);
}