package com.juju.sport.order.mapper;

import com.juju.sport.order.pojo.UserOrder;
import com.juju.sport.order.pojo.UserOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    int countByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    int deleteByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    int insert(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    int insertSelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    List<UserOrder> selectByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    UserOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserOrder record, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    int updateByExample(@Param("record") UserOrder record, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    int updateByPrimaryKeySelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_user_order_mapping
     *
     * @mbggenerated Wed May 13 16:07:45 CST 2015
     */
    int updateByPrimaryKey(UserOrder record);
}