package com.juju.sport.stadium.pojo;

import java.util.Date;

public class SpaceOpenTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.id
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.user_account_id
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private String userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.space_id
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private String spaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.open_week
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private Short openWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.price
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.start_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.end_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.create_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.last_update_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_space_opentime.stat
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.id
     *
     * @return the value of juju_space_opentime.id
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.id
     *
     * @param id the value for juju_space_opentime.id
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.user_account_id
     *
     * @return the value of juju_space_opentime.user_account_id
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public String getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.user_account_id
     *
     * @param userAccountId the value for juju_space_opentime.user_account_id
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setUserAccountId(String userAccountId) {
        this.userAccountId = userAccountId == null ? null : userAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.space_id
     *
     * @return the value of juju_space_opentime.space_id
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public String getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.space_id
     *
     * @param spaceId the value for juju_space_opentime.space_id
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setSpaceId(String spaceId) {
        this.spaceId = spaceId == null ? null : spaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.open_week
     *
     * @return the value of juju_space_opentime.open_week
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public Short getOpenWeek() {
        return openWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.open_week
     *
     * @param openWeek the value for juju_space_opentime.open_week
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setOpenWeek(Short openWeek) {
        this.openWeek = openWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.price
     *
     * @return the value of juju_space_opentime.price
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.price
     *
     * @param price the value for juju_space_opentime.price
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.start_time
     *
     * @return the value of juju_space_opentime.start_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.start_time
     *
     * @param startTime the value for juju_space_opentime.start_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.end_time
     *
     * @return the value of juju_space_opentime.end_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.end_time
     *
     * @param endTime the value for juju_space_opentime.end_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.create_time
     *
     * @return the value of juju_space_opentime.create_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.create_time
     *
     * @param createTime the value for juju_space_opentime.create_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.last_update_time
     *
     * @return the value of juju_space_opentime.last_update_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.last_update_time
     *
     * @param lastUpdateTime the value for juju_space_opentime.last_update_time
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_space_opentime.stat
     *
     * @return the value of juju_space_opentime.stat
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_space_opentime.stat
     *
     * @param stat the value for juju_space_opentime.stat
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}