package com.juju.sport.stadium.pojo;

import java.util.Date;

public class VenuesDayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info.id
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info.venuesid
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    private String venuesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info.daytime
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    private String daytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info.onliner
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    private Integer onliner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info.state
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info.create_time
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info.last_update_time
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info.stat
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info.id
     *
     * @return the value of juju_venues_day_info.id
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info.id
     *
     * @param id the value for juju_venues_day_info.id
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info.venuesid
     *
     * @return the value of juju_venues_day_info.venuesid
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public String getVenuesid() {
        return venuesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info.venuesid
     *
     * @param venuesid the value for juju_venues_day_info.venuesid
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public void setVenuesid(String venuesid) {
        this.venuesid = venuesid == null ? null : venuesid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info.daytime
     *
     * @return the value of juju_venues_day_info.daytime
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public String getDaytime() {
        return daytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info.daytime
     *
     * @param daytime the value for juju_venues_day_info.daytime
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public void setDaytime(String daytime) {
        this.daytime = daytime == null ? null : daytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info.onliner
     *
     * @return the value of juju_venues_day_info.onliner
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public Integer getOnliner() {
        return onliner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info.onliner
     *
     * @param onliner the value for juju_venues_day_info.onliner
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public void setOnliner(Integer onliner) {
        this.onliner = onliner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info.state
     *
     * @return the value of juju_venues_day_info.state
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info.state
     *
     * @param state the value for juju_venues_day_info.state
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info.create_time
     *
     * @return the value of juju_venues_day_info.create_time
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info.create_time
     *
     * @param createTime the value for juju_venues_day_info.create_time
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info.last_update_time
     *
     * @return the value of juju_venues_day_info.last_update_time
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info.last_update_time
     *
     * @param lastUpdateTime the value for juju_venues_day_info.last_update_time
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info.stat
     *
     * @return the value of juju_venues_day_info.stat
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info.stat
     *
     * @param stat the value for juju_venues_day_info.stat
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}