package com.juju.sport.stadium.pojo;

import java.util.Date;

public class VenuesDayInfoList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info_list.id
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info_list.venuesid
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    private String venuesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info_list.card_no
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info_list.daytime
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    private String daytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info_list.create_time
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info_list.last_update_time
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_venues_day_info_list.stat
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info_list.id
     *
     * @return the value of juju_venues_day_info_list.id
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info_list.id
     *
     * @param id the value for juju_venues_day_info_list.id
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info_list.venuesid
     *
     * @return the value of juju_venues_day_info_list.venuesid
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public String getVenuesid() {
        return venuesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info_list.venuesid
     *
     * @param venuesid the value for juju_venues_day_info_list.venuesid
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public void setVenuesid(String venuesid) {
        this.venuesid = venuesid == null ? null : venuesid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info_list.card_no
     *
     * @return the value of juju_venues_day_info_list.card_no
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info_list.card_no
     *
     * @param cardNo the value for juju_venues_day_info_list.card_no
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info_list.daytime
     *
     * @return the value of juju_venues_day_info_list.daytime
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public String getDaytime() {
        return daytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info_list.daytime
     *
     * @param daytime the value for juju_venues_day_info_list.daytime
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public void setDaytime(String daytime) {
        this.daytime = daytime == null ? null : daytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info_list.create_time
     *
     * @return the value of juju_venues_day_info_list.create_time
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info_list.create_time
     *
     * @param createTime the value for juju_venues_day_info_list.create_time
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info_list.last_update_time
     *
     * @return the value of juju_venues_day_info_list.last_update_time
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info_list.last_update_time
     *
     * @param lastUpdateTime the value for juju_venues_day_info_list.last_update_time
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_venues_day_info_list.stat
     *
     * @return the value of juju_venues_day_info_list.stat
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_venues_day_info_list.stat
     *
     * @param stat the value for juju_venues_day_info_list.stat
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}