package com.juju.sport.user.pojo;

import java.util.Date;

public class Medal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_medal.id
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_medal.type
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_medal.level
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_medal.name
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_medal.logo
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_medal.create_time
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_medal.last_update_time
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_medal.stat
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_medal.id
     *
     * @return the value of juju_medal.id
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_medal.id
     *
     * @param id the value for juju_medal.id
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_medal.type
     *
     * @return the value of juju_medal.type
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_medal.type
     *
     * @param type the value for juju_medal.type
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_medal.level
     *
     * @return the value of juju_medal.level
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_medal.level
     *
     * @param level the value for juju_medal.level
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_medal.name
     *
     * @return the value of juju_medal.name
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_medal.name
     *
     * @param name the value for juju_medal.name
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_medal.logo
     *
     * @return the value of juju_medal.logo
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_medal.logo
     *
     * @param logo the value for juju_medal.logo
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_medal.create_time
     *
     * @return the value of juju_medal.create_time
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_medal.create_time
     *
     * @param createTime the value for juju_medal.create_time
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_medal.last_update_time
     *
     * @return the value of juju_medal.last_update_time
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_medal.last_update_time
     *
     * @param lastUpdateTime the value for juju_medal.last_update_time
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_medal.stat
     *
     * @return the value of juju_medal.stat
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_medal.stat
     *
     * @param stat the value for juju_medal.stat
     *
     * @mbggenerated Mon May 04 14:16:37 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}