package com.juju.sport.user.pojo;

import java.util.Date;

public class TeamScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_team_score.id
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_team_score.team_id
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    private String teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_team_score.other_team_id
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    private String otherTeamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_team_score.score
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_team_score.create_time
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_team_score.last_update_time
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_team_score.stat
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_team_score.id
     *
     * @return the value of juju_team_score.id
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_team_score.id
     *
     * @param id the value for juju_team_score.id
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_team_score.team_id
     *
     * @return the value of juju_team_score.team_id
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_team_score.team_id
     *
     * @param teamId the value for juju_team_score.team_id
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_team_score.other_team_id
     *
     * @return the value of juju_team_score.other_team_id
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public String getOtherTeamId() {
        return otherTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_team_score.other_team_id
     *
     * @param otherTeamId the value for juju_team_score.other_team_id
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public void setOtherTeamId(String otherTeamId) {
        this.otherTeamId = otherTeamId == null ? null : otherTeamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_team_score.score
     *
     * @return the value of juju_team_score.score
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_team_score.score
     *
     * @param score the value for juju_team_score.score
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_team_score.create_time
     *
     * @return the value of juju_team_score.create_time
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_team_score.create_time
     *
     * @param createTime the value for juju_team_score.create_time
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_team_score.last_update_time
     *
     * @return the value of juju_team_score.last_update_time
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_team_score.last_update_time
     *
     * @param lastUpdateTime the value for juju_team_score.last_update_time
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_team_score.stat
     *
     * @return the value of juju_team_score.stat
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_team_score.stat
     *
     * @param stat the value for juju_team_score.stat
     *
     * @mbggenerated Tue Mar 24 18:24:43 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}