package com.juju.sport.family.pojo;

import java.util.Date;

public class SportExamination {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_examination.id
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_examination.type
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_examination.title
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_examination.img_url
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_examination.create_time
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_examination.id
     *
     * @return the value of juju_sport_examination.id
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_examination.id
     *
     * @param id the value for juju_sport_examination.id
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_examination.type
     *
     * @return the value of juju_sport_examination.type
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_examination.type
     *
     * @param type the value for juju_sport_examination.type
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_examination.title
     *
     * @return the value of juju_sport_examination.title
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_examination.title
     *
     * @param title the value for juju_sport_examination.title
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_examination.img_url
     *
     * @return the value of juju_sport_examination.img_url
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_examination.img_url
     *
     * @param imgUrl the value for juju_sport_examination.img_url
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_examination.create_time
     *
     * @return the value of juju_sport_examination.create_time
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_examination.create_time
     *
     * @param createTime the value for juju_sport_examination.create_time
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}