package com.juju.sport.order.pojo;

import java.util.Date;

public class OrderItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.order_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.order_no
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.date
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.order_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.end_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.space_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String spaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.space_name
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String spaceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.valid_code
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String validCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.user_account_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.owner_account_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String ownerAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.telephone
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.order_total
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private Integer orderTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.create_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.last_update_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.week
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private Integer week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.stat
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.user_account_name
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String userAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.order_status
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.rand_code
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private String randCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders_items.use_type
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    private Integer useType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.id
     *
     * @return the value of juju_orders_items.id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.id
     *
     * @param id the value for juju_orders_items.id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.order_id
     *
     * @return the value of juju_orders_items.order_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.order_id
     *
     * @param orderId the value for juju_orders_items.order_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.order_no
     *
     * @return the value of juju_orders_items.order_no
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.order_no
     *
     * @param orderNo the value for juju_orders_items.order_no
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.date
     *
     * @return the value of juju_orders_items.date
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.date
     *
     * @param date the value for juju_orders_items.date
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.order_time
     *
     * @return the value of juju_orders_items.order_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.order_time
     *
     * @param orderTime the value for juju_orders_items.order_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.end_time
     *
     * @return the value of juju_orders_items.end_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.end_time
     *
     * @param endTime the value for juju_orders_items.end_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.space_id
     *
     * @return the value of juju_orders_items.space_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.space_id
     *
     * @param spaceId the value for juju_orders_items.space_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setSpaceId(String spaceId) {
        this.spaceId = spaceId == null ? null : spaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.space_name
     *
     * @return the value of juju_orders_items.space_name
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getSpaceName() {
        return spaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.space_name
     *
     * @param spaceName the value for juju_orders_items.space_name
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setSpaceName(String spaceName) {
        this.spaceName = spaceName == null ? null : spaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.valid_code
     *
     * @return the value of juju_orders_items.valid_code
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getValidCode() {
        return validCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.valid_code
     *
     * @param validCode the value for juju_orders_items.valid_code
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setValidCode(String validCode) {
        this.validCode = validCode == null ? null : validCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.user_account_id
     *
     * @return the value of juju_orders_items.user_account_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.user_account_id
     *
     * @param userAccountId the value for juju_orders_items.user_account_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setUserAccountId(String userAccountId) {
        this.userAccountId = userAccountId == null ? null : userAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.owner_account_id
     *
     * @return the value of juju_orders_items.owner_account_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getOwnerAccountId() {
        return ownerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.owner_account_id
     *
     * @param ownerAccountId the value for juju_orders_items.owner_account_id
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setOwnerAccountId(String ownerAccountId) {
        this.ownerAccountId = ownerAccountId == null ? null : ownerAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.telephone
     *
     * @return the value of juju_orders_items.telephone
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.telephone
     *
     * @param telephone the value for juju_orders_items.telephone
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.order_total
     *
     * @return the value of juju_orders_items.order_total
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public Integer getOrderTotal() {
        return orderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.order_total
     *
     * @param orderTotal the value for juju_orders_items.order_total
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setOrderTotal(Integer orderTotal) {
        this.orderTotal = orderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.create_time
     *
     * @return the value of juju_orders_items.create_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.create_time
     *
     * @param createTime the value for juju_orders_items.create_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.last_update_time
     *
     * @return the value of juju_orders_items.last_update_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.last_update_time
     *
     * @param lastUpdateTime the value for juju_orders_items.last_update_time
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.week
     *
     * @return the value of juju_orders_items.week
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.week
     *
     * @param week the value for juju_orders_items.week
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.stat
     *
     * @return the value of juju_orders_items.stat
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.stat
     *
     * @param stat the value for juju_orders_items.stat
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.user_account_name
     *
     * @return the value of juju_orders_items.user_account_name
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getUserAccountName() {
        return userAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.user_account_name
     *
     * @param userAccountName the value for juju_orders_items.user_account_name
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setUserAccountName(String userAccountName) {
        this.userAccountName = userAccountName == null ? null : userAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.order_status
     *
     * @return the value of juju_orders_items.order_status
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.order_status
     *
     * @param orderStatus the value for juju_orders_items.order_status
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.rand_code
     *
     * @return the value of juju_orders_items.rand_code
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public String getRandCode() {
        return randCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.rand_code
     *
     * @param randCode the value for juju_orders_items.rand_code
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setRandCode(String randCode) {
        this.randCode = randCode == null ? null : randCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders_items.use_type
     *
     * @return the value of juju_orders_items.use_type
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public Integer getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders_items.use_type
     *
     * @param useType the value for juju_orders_items.use_type
     *
     * @mbggenerated Fri May 29 18:19:10 CST 2015
     */
    public void setUseType(Integer useType) {
        this.useType = useType;
    }
}