package com.juju.sport.order.pojo;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.id
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.order_no
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.telephone
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.order_total
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private Integer orderTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.order_status
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.payment_status
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private Integer paymentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.user_account_id
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private String userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.owner_account_id
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private String ownerAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.order_time
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.create_time
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.last_update_time
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_orders.stat
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.id
     *
     * @return the value of juju_orders.id
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.id
     *
     * @param id the value for juju_orders.id
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.order_no
     *
     * @return the value of juju_orders.order_no
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.order_no
     *
     * @param orderNo the value for juju_orders.order_no
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.telephone
     *
     * @return the value of juju_orders.telephone
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.telephone
     *
     * @param telephone the value for juju_orders.telephone
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.order_total
     *
     * @return the value of juju_orders.order_total
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public Integer getOrderTotal() {
        return orderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.order_total
     *
     * @param orderTotal the value for juju_orders.order_total
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setOrderTotal(Integer orderTotal) {
        this.orderTotal = orderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.order_status
     *
     * @return the value of juju_orders.order_status
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.order_status
     *
     * @param orderStatus the value for juju_orders.order_status
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.payment_status
     *
     * @return the value of juju_orders.payment_status
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public Integer getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.payment_status
     *
     * @param paymentStatus the value for juju_orders.payment_status
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setPaymentStatus(Integer paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.user_account_id
     *
     * @return the value of juju_orders.user_account_id
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public String getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.user_account_id
     *
     * @param userAccountId the value for juju_orders.user_account_id
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setUserAccountId(String userAccountId) {
        this.userAccountId = userAccountId == null ? null : userAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.owner_account_id
     *
     * @return the value of juju_orders.owner_account_id
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public String getOwnerAccountId() {
        return ownerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.owner_account_id
     *
     * @param ownerAccountId the value for juju_orders.owner_account_id
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setOwnerAccountId(String ownerAccountId) {
        this.ownerAccountId = ownerAccountId == null ? null : ownerAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.order_time
     *
     * @return the value of juju_orders.order_time
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.order_time
     *
     * @param orderTime the value for juju_orders.order_time
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.create_time
     *
     * @return the value of juju_orders.create_time
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.create_time
     *
     * @param createTime the value for juju_orders.create_time
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.last_update_time
     *
     * @return the value of juju_orders.last_update_time
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.last_update_time
     *
     * @param lastUpdateTime the value for juju_orders.last_update_time
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_orders.stat
     *
     * @return the value of juju_orders.stat
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_orders.stat
     *
     * @param stat the value for juju_orders.stat
     *
     * @mbggenerated Fri Mar 27 10:37:13 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}