package com.juju.sport.family.mapper;

import com.juju.sport.family.pojo.Health;
import com.juju.sport.family.pojo.HealthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HealthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    int countByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    int deleteByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    int insert(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    int insertSelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    List<Health> selectByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    Health selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") Health record, @Param("example") HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    int updateByExample(@Param("record") Health record, @Param("example") HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    int updateByPrimaryKeySelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_health
     *
     * @mbggenerated Wed Apr 08 18:35:45 CST 2015
     */
    int updateByPrimaryKey(Health record);
}