package com.juju.sport.base.mapper;

import com.juju.sport.base.pojo.Addresses;
import com.juju.sport.base.pojo.AddressesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddressesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    int countByExample(AddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    int deleteByExample(AddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    int insert(Addresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    int insertSelective(Addresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    List<Addresses> selectByExample(AddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    Addresses selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") Addresses record, @Param("example") AddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    int updateByExample(@Param("record") Addresses record, @Param("example") AddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    int updateByPrimaryKeySelective(Addresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_addresses
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    int updateByPrimaryKey(Addresses record);
}