package com.juju.sport.base.mapper;

import com.juju.sport.base.pojo.AppVersion;
import com.juju.sport.base.pojo.AppVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    int countByExample(AppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    int deleteByExample(AppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    int insert(AppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    int insertSelective(AppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    List<AppVersion> selectByExample(AppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    AppVersion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") AppVersion record, @Param("example") AppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    int updateByExample(@Param("record") AppVersion record, @Param("example") AppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    int updateByPrimaryKeySelective(AppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_app_version
     *
     * @mbggenerated Thu May 07 09:24:48 CST 2015
     */
    int updateByPrimaryKey(AppVersion record);
}