package com.juju.sport.base.mapper;

import com.juju.sport.base.pojo.CardInfo;
import com.juju.sport.base.pojo.CardInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    int countByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    int deleteByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    int insert(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    int insertSelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    List<CardInfo> selectByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    CardInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") CardInfo record, @Param("example") CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    int updateByExample(@Param("record") CardInfo record, @Param("example") CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    int updateByPrimaryKeySelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_card_info
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    int updateByPrimaryKey(CardInfo record);
}