package com.juju.sport.base.mapper;

import com.juju.sport.base.pojo.ImageInfo;
import com.juju.sport.base.pojo.ImageInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    int countByExample(ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    int deleteByExample(ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    int insert(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    int insertSelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    List<ImageInfo> selectByExample(ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    ImageInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") ImageInfo record, @Param("example") ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    int updateByExample(@Param("record") ImageInfo record, @Param("example") ImageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    int updateByPrimaryKeySelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_image_info
     *
     * @mbggenerated Wed Apr 15 13:18:17 CST 2015
     */
    int updateByPrimaryKey(ImageInfo record);
}