package com.juju.sport.user.mapper;

import com.juju.sport.user.pojo.Team;
import com.juju.sport.user.pojo.TeamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    int countByExample(TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    int deleteByExample(TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    int insertSelective(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    List<Team> selectByExample(TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    Team selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") Team record, @Param("example") TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    int updateByExample(@Param("record") Team record, @Param("example") TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    int updateByPrimaryKeySelective(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_team
     *
     * @mbggenerated Sat May 02 11:01:39 CST 2015
     */
    int updateByPrimaryKey(Team record);
}