package com.juju.sport.sync.mapper;

import com.juju.sport.sync.pojo.DataSync;
import com.juju.sport.sync.pojo.DataSyncExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataSyncMapper {
	
	List<DataSync> findAll(Integer max);
	
	List<DataSync> findAllErrRecord(@Param("start")Integer start, @Param("max")Integer max);
	
	int updateErrorInfo(@Param("id")Integer id, @Param("info")String info);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    int countByExample(DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    int deleteByExample(DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    int insert(DataSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    int insertSelective(DataSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    List<DataSync> selectByExample(DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    DataSync selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    int updateByExampleSelective(@Param("record") DataSync record, @Param("example") DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    int updateByExample(@Param("record") DataSync record, @Param("example") DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    int updateByPrimaryKeySelective(DataSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_sync
     *
     * @mbggenerated Thu Mar 26 14:38:16 CST 2015
     */
    int updateByPrimaryKey(DataSync record);
}