package com.juju.sport.stadium.mapper;

import com.juju.sport.stadium.pojo.SpaceOpenTime;
import com.juju.sport.stadium.pojo.SpaceOpenTimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpaceOpenTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    int countByExample(SpaceOpenTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    int deleteByExample(SpaceOpenTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    int insert(SpaceOpenTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    int insertSelective(SpaceOpenTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    List<SpaceOpenTime> selectByExample(SpaceOpenTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    SpaceOpenTime selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") SpaceOpenTime record, @Param("example") SpaceOpenTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    int updateByExample(@Param("record") SpaceOpenTime record, @Param("example") SpaceOpenTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    int updateByPrimaryKeySelective(SpaceOpenTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_space_opentime
     *
     * @mbggenerated Fri May 08 11:55:32 CST 2015
     */
    int updateByPrimaryKey(SpaceOpenTime record);
}