package com.juju.sport.stadium.mapper;

import com.juju.sport.stadium.pojo.VenuesDayInfo;
import com.juju.sport.stadium.pojo.VenuesDayInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VenuesDayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    int countByExample(VenuesDayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    int deleteByExample(VenuesDayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    int insert(VenuesDayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    int insertSelective(VenuesDayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    List<VenuesDayInfo> selectByExample(VenuesDayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    VenuesDayInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") VenuesDayInfo record, @Param("example") VenuesDayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    int updateByExample(@Param("record") VenuesDayInfo record, @Param("example") VenuesDayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    int updateByPrimaryKeySelective(VenuesDayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info
     *
     * @mbggenerated Thu May 21 16:43:01 CST 2015
     */
    int updateByPrimaryKey(VenuesDayInfo record);
}