package com.juju.sport.stadium.mapper;

import com.juju.sport.stadium.pojo.VenuesDayInfoList;
import com.juju.sport.stadium.pojo.VenuesDayInfoListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VenuesDayInfoListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    int countByExample(VenuesDayInfoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    int deleteByExample(VenuesDayInfoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    int insert(VenuesDayInfoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    int insertSelective(VenuesDayInfoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    List<VenuesDayInfoList> selectByExample(VenuesDayInfoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    VenuesDayInfoList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") VenuesDayInfoList record, @Param("example") VenuesDayInfoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    int updateByExample(@Param("record") VenuesDayInfoList record, @Param("example") VenuesDayInfoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    int updateByPrimaryKeySelective(VenuesDayInfoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juju_venues_day_info_list
     *
     * @mbggenerated Tue May 26 16:48:48 CST 2015
     */
    int updateByPrimaryKey(VenuesDayInfoList record);
}