package com.juju.sport.base.pojo;

import java.util.Date;

public class CardInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.id
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.card_no
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.card_name
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.card_id
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.telephone
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.age
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.address
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.contact
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.create_time
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.last_update_time
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_card_info.stat
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.id
     *
     * @return the value of juju_card_info.id
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.id
     *
     * @param id the value for juju_card_info.id
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.card_no
     *
     * @return the value of juju_card_info.card_no
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.card_no
     *
     * @param cardNo the value for juju_card_info.card_no
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.card_name
     *
     * @return the value of juju_card_info.card_name
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.card_name
     *
     * @param cardName the value for juju_card_info.card_name
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.card_id
     *
     * @return the value of juju_card_info.card_id
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.card_id
     *
     * @param cardId the value for juju_card_info.card_id
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.telephone
     *
     * @return the value of juju_card_info.telephone
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.telephone
     *
     * @param telephone the value for juju_card_info.telephone
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.age
     *
     * @return the value of juju_card_info.age
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.age
     *
     * @param age the value for juju_card_info.age
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.address
     *
     * @return the value of juju_card_info.address
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.address
     *
     * @param address the value for juju_card_info.address
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.contact
     *
     * @return the value of juju_card_info.contact
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.contact
     *
     * @param contact the value for juju_card_info.contact
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.create_time
     *
     * @return the value of juju_card_info.create_time
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.create_time
     *
     * @param createTime the value for juju_card_info.create_time
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.last_update_time
     *
     * @return the value of juju_card_info.last_update_time
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.last_update_time
     *
     * @param lastUpdateTime the value for juju_card_info.last_update_time
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_card_info.stat
     *
     * @return the value of juju_card_info.stat
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_card_info.stat
     *
     * @param stat the value for juju_card_info.stat
     *
     * @mbggenerated Mon May 11 17:50:53 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}