package com.juju.sport.base.pojo;

import java.util.Date;

public class SportType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_type.id
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_type.sport_name
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    private String sportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_type.create_time
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_type.last_update_time
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juju_sport_type.stat
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_type.id
     *
     * @return the value of juju_sport_type.id
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_type.id
     *
     * @param id the value for juju_sport_type.id
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_type.sport_name
     *
     * @return the value of juju_sport_type.sport_name
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public String getSportName() {
        return sportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_type.sport_name
     *
     * @param sportName the value for juju_sport_type.sport_name
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public void setSportName(String sportName) {
        this.sportName = sportName == null ? null : sportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_type.create_time
     *
     * @return the value of juju_sport_type.create_time
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_type.create_time
     *
     * @param createTime the value for juju_sport_type.create_time
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_type.last_update_time
     *
     * @return the value of juju_sport_type.last_update_time
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_type.last_update_time
     *
     * @param lastUpdateTime the value for juju_sport_type.last_update_time
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juju_sport_type.stat
     *
     * @return the value of juju_sport_type.stat
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juju_sport_type.stat
     *
     * @param stat the value for juju_sport_type.stat
     *
     * @mbggenerated Tue Mar 24 13:25:48 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}