package com.juju.sport.admin.manager.mapper;

import com.juju.sport.admin.manager.pojo.AccountAction;
import com.juju.sport.admin.manager.pojo.AccountActionExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AccountActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    int countByExample(AccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    int deleteByExample(AccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    int insert(AccountAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    int insertSelective(AccountAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    List<AccountAction> selectByExample(AccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    AccountAction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    int updateByExampleSelective(@Param("record") AccountAction record, @Param("example") AccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    int updateByExample(@Param("record") AccountAction record, @Param("example") AccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    int updateByPrimaryKeySelective(AccountAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account_action
     *
     * @mbggenerated Fri Aug 29 17:07:17 CST 2014
     */
    int updateByPrimaryKey(AccountAction record);
}